### PR TITLE
#112: fixed javadoc file copy instances

### PR DESCRIPTION
**Pull request by dbenn**
Fixed the file copying elements in Ant build file.

### CODE REVIEW

**Comment by yorkpf** [comment]
David: Downloaded zip file seems to work as it should. Thanks. For my part, can I safely just replace my current (non-working) vstar_docs with this newer version? Paul

**Review by yorkpf — COMMENTED** [review]
OK. I can read the new downloaded API.

**Comment by mpyat2** [comment]
Win distribution: created successfully, both vstar-<version>-win.zip and VStarSetup_<version>.exe.
As I see, it is required to run 'ant javadoc' before creating a distribution package (i.e. ant win).
What do you think about making "win", "bash", "mac" targets dependent on "javadoc" target?

**Comment by dbenn** [comment]
When you're happy with the dependent targets @mpyat2, I'll merge this one.

**Comment by mpyat2** [comment]
@dbenn Yes all is OK! Thank you!

**Pull request merged**
