### PR TITLE
--default-look-and-feel command line option

### PR DESCRIPTION
**Pull request by mpyat2**
This option disables the setting of the 'native' to the system look and feel.

Linux:
./VStar.sh --default-look-and-feel

Windows:
VStar.exe --default-look-and-feel

### CODE REVIEW

**Comment by dbenn** [comment]
`./VStar.sh --default-look-and-feel` will also work for Mac OS X if run from the command-line.

**Review by dbenn — APPROVED** [review]
Looks good. I can't test whether this fixes the problem seen by some with file choosers. Getting a snapshot release for affected users out would be good. Thanks!

**Comment by mpyat2** [comment]
> Getting a snapshot release for affected users out would be good.
The snapshot is here https://drive.google.com/drive/folders/1feN5uA9WOI8chDStdGqWnuMUMT_FZV_l?usp=sharing
After unpacking vstar-bash.zip, do chmod 755 VStar.sh please.

**Comment by dbenn** [comment]
@yorkpf Would you be able to try the vstar-bash.zip Max mentions above to see whether it fixes the problem you saw in #180 ? Let us know if you need assistance.

**Comment by mpyat2** [comment]
Hi folks, you can find the zip here: https://drive.google.com/drive/folders/1feN5uA9WOI8chDStdGqWnuMUMT_FZV_l?usp=sharing

**Comment by yorkpf** [comment]
Looks like it works OK, David.

Paul

**Comment by dbenn** [comment]
Good! Thanks @yorkpf. So the file file dialog error where files didn't show up on the Mac is fixed by this?

**Comment by yorkpf** [comment]
It certainly seems to be. Should I start using this new dev version of VStar?

**Comment by dbenn** [comment]
If you would like to and it solves the problem you were seeing @yorkpf. A new release is being worked on to fix a bug introduced in the current release though relating to Fourier model uncertainty calculation.

**Pull request merged**
