### PR TITLE
initialization of dtvar added in TSBase.statcomp()

### PR DESCRIPTION
**Pull request by mpyat2**
See #459

### CODE REVIEW

**Comment by mpyat2** [comment]
Hi @dbenn 
I see errors in unit tests, inspecting them (FreqRangeTopHitsDcDftTest.java). Top hits were changed with the fix.

**Comment by dbenn** [comment]
I'd expect some UT failures with this change.

**Comment by mpyat2** [comment]
Failed:
1) CleanestTest
2) DcDftTest
3) FreqRangeTopHitsDcDftTest
4) StdScanTopHitsDcDftTest
I'll work on them.

**Comment by mpyat2** [comment]
I updated the tests. Data for the tests were taken from Peranso output, except for the last two tests in CleanestTest.java:
testRefineOneFreqAndOneVariablePeriod()
and
testRefineOneFreqAndOneLockedPeriod()
For these two tests, I took data from the VStar output with the applied fix. It is not fair, but I could not find the exact analog in Peranso's CLEANest Workbench. I think it is not critical because, in each test, only power values change by a minor factor after the fix; the relative power values for all peaks are preserved.

**Comment by dbenn** [comment]
Thanks @mpyat2 ! Looks good so far. Here's a case that shows that sometimes a small line-of-code count can have changes that impact more test code than product code. ;) Working through it.

**Review by dbenn — APPROVED** [review]
Thanks @mpyat2. Appreciate it! This one wins the prize for smallest code change leading to largest UT change. :)

**Pull request merged**
