### PR TITLE
#129: removed deprecated VeLa expression listener

### PR DESCRIPTION
**Pull request by dbenn**
Hi Paul. Nothing too much to check here except removal of a source file. Thanks.

### CODE REVIEW

**Comment by yorkpf** [comment]
Looks good, David.

**Review by yorkpf — COMMENTED** [review]
Looks fine, David

**Comment by dbenn** [comment]
Thanks Paul. Happy for me to merge and close then?

**Comment by yorkpf** [comment]
Yep, sorry .

**Comment by dbenn** [comment]
No worries. Thanks.

**Pull request merged**
