### PR TITLE
375 move to auth0

### PR DESCRIPTION
**Pull request by dbenn**
Hi @mpyat2 

Please have a look at the authentication changes.

### CODE REVIEW

**Comment by mpyat2** [comment]
Hi @dbenn 

When I pass the authentication, I'm asked to log in to AAVSO. I CAN do it via Google (the second option), yet I cannot log in via the AAVSO credentials. When I log in to the AAVSO site, I use a nickname (not an e-mail address). However, neither nickname nor e-mail address does not work here.

image

**Comment by dbenn** [comment]
Yes, a reasonable question @mpyat2. I've asked @aru-py a question about this in #375.

**Comment by aru-py** [comment]
@mpyat2 The AAVSO will be migrating accounts to the Auth0 platform in mid-January. Until then, please continue to use the current version of VStar.

**Comment by dbenn** [comment]
Thanks @aru-py, @mpyat2 is reviewing the code changes in preparation for a new release!

Do we have a date in January to aim for?

**Comment by aru-py** [comment]
@dbenn Wonderful!

Not yet. We aim to have it finalized by next week and will announce it to our members shortly thereafter.

**Review by mpyat2 — APPROVED** [review]

**Pull request merged**
