### PR TITLE
#155: removed Delete All button and added an All? checkbox to apply operations to Install, Update, and Delete buttons

### PR DESCRIPTION
**Pull request by dbenn**

### CODE REVIEW

**Comment by mpyat2** [comment]
Hi @dbenn ,
I've made some changes. Please see the commit.
First, I've made Install/Update/Delete methods more self-consistent; made some cosmetic fixes, and added a custom renderer to the plugin list: now installed plugins are bolded.

**Comment by dbenn** [comment]
Thanks for all the changes/fixes @mpyat2. I don't know why I had a loop in `setAllButtonStates()`! Thanks for spotting and fixing that. Upon reflection, it's clear that the method name was not right either, so I've changed that and the comment above the method.

**Comment by mpyat2** [comment]
Hi @dbenn , since Update and Install do the same if 'All?' is in an active state, I've made a minor change that disables 'Update' when 'All?' is checked.

**Comment by mpyat2** [comment]
Well, another minor fix (accessing ListModel in a background thread). I hope it's all for now.

**Comment by dbenn** [comment]
Will allow a bit more time for us to test this out before merging.

**Comment by mpyat2** [comment]
ok

**Review by mpyat2 — APPROVED** [review]

**Pull request merged**
