### PR TITLE
PlotControlDialog: "Invert Series Order?" checkbox.

### PR DESCRIPTION
**Pull request by mpyat2**
PlotControlDialog: "Invert Series Order?" checkbox added.

"Invert Series Order?" _partially_ resolves issue #108. In simple cases, it may be sufficient. Series are inverted by default in VStar .
When there are many overlapping series loaded, it is also useful to look at them "from the other side"
VStar

Also, color equality check trivial fix in ChartPropertiesSelectionPane was made.

### CODE REVIEW

**Comment by mpyat2** [comment]
@dbenn, @clkotnik What do you think about it?

**Comment by dbenn** [comment]
Sorry @mpyat2. I thought I had replied. I like it.

**Review by dbenn — APPROVED** [review]

**Comment by dbenn** [comment]
@mpyat2: Cliff may be busy. Happy to merge this if you like.

**Review by dbenn — CHANGES_REQUESTED** [review]
@mpyat2 I just noticed that while you have added the locale property:
~~~
INVERT_SERIES_ORDER=Invert Series Order?
~~~
this has not been added to all strings files, i.e. the French and Spanish ones. I can give you the emails of people in AAVSO who have done translations for me. In some simple cases I will do it myself. In the worst case, I will sometimes just put the English property in all the strings files with a view to translating in a future release.

**Comment by mpyat2** [comment]
Oh yes, I forgot about other language files. Yes, please give me translators e-mails. I will contact them.
I guess the Spanish translator is Sabastian Otero?

**Comment by mpyat2** [comment]
@dbenn 
INVERT_SERIES_ORDER= message added to the Spanish and French translations.

**Review by dbenn — APPROVED** [review]

**Pull request merged**
