### PR TITLE
Vstar windows installer

### PR DESCRIPTION
**Pull request by mpyat2**
1) VStar.exe launcher replaced by a new one: no black console window anymore. JRE parameters (i.e. memory management) are configured via VStar.ini (self-explanatory, I hope)
2) VStar.bat changed slightly. It can be used to test if JRE parameters are correct (better JRE startup error handling in the console mode) and to see VStar debug console output.
3) Windows installer has not been included yet. After unpacking vstar-win.zip, a user can launch CreateVStarShortcuts.vbs script to create desktop and main menu shortcuts to VStar.exe
4) windows_installer folder added to doc folder with How to install VStar under Windows.* documents.

This should be tested on a Windows machine. It works for me yet more tests needed, I think.

### CODE REVIEW

**Comment by mpyat2** [comment]
build-win-installer.xml and several other files needed to create an executable Windows installer (VStarSetup_X.YY.Z.exe, where X.YY.Z is a VStar version) have been added.
While creating EXE-installer, VStar files are taken from vstar-win.zip bundle (it must exist before build-win-installer.xml execution). This guarantees that VStar files are the same as in the original distribution (*.zip is simply repacked to EXE-installer)

**Comment by dbenn** [comment]
Looks good @mpyat2  I've looked at the Ant file. Just let me know when you're ready to merge. So, are both Pascal and Basic used by the Inno software?

**Comment by mpyat2** [comment]
@dbenn 
Hi David,
Could you please merge 'vstar-windows-installer' with the trunk?

**Comment by dbenn** [comment]
Merged and branch deleted. Thanks @mpyat2

**Comment by mpyat2** [comment]
Thank you @dbenn

**Pull request merged**
