### PR TITLE
All plugins included in the Windows installer.

### PR DESCRIPTION
**Pull request by mpyat2**
Hi David,
These are Windows-only-related changes (Windows installer with all plugins).
I'm not sure who could test it.
Probably, after the merging, I could create the executable installer and put it somewhere to test.
Now I'm going to update the recipe ( https://github.com/AAVSO/VStar/wiki/Installation-Recipes )

### CODE REVIEW

**Comment by dbenn** [comment]
Perhaps @SaraAAVSO or @clkotnik would be able to test the installer @mpyat2 ?

**Comment by dbenn** [comment]
We could do a separate branch to update the VStar version @mpyat2 or perhaps we can just do it on this branch?

**Review by dbenn — APPROVED** [review]

**Review by dbenn — APPROVED** [review]

**Comment by SaraAAVSO** [comment]
Hi David,

John should be able to test the Windows installer on his machine. How do 
we get it from GitHub?

Thanks,
Sara

**Comment by dbenn** [comment]
I'll let @mpyat2 respond @SaraAAVSO

**Comment by dbenn** [comment]
The Java CI error above appears to have been a transient git repo access error.

**Comment by mpyat2** [comment]
I've just rerun the tests, all is ok now

**Comment by dbenn** [comment]
Yes, I think it was just a transient failure as opposed to anything else. Thanks Max.

**Review by dbenn — APPROVED** [review]

**Pull request merged**
