### PR TITLE
#390: added check for zero (or close to) min/max range in WWZ plot pane

### PR DESCRIPTION
**Pull request by dbenn**
Please check this works for you after the fix and review code @mpyat2

### CODE REVIEW

**Comment by mpyat2** [comment]
Hi @dbenn , I see unit test errors...

**Comment by dbenn** [comment]
> Hi @dbenn , I see unit test errors...

Yes indeed, odd since I changed a README.

**Comment by dbenn** [comment]
Seems fine now @mpyat2

**Comment by mpyat2** [comment]
Ho @dbenn ,
Everything is OK!

**Review by mpyat2 — APPROVED** [review]

**Pull request merged**
