### PR TITLE
Issue 195 label light curve

### PR DESCRIPTION
**Pull request by dbenn**
@mpyat2 further to #51 which we've just fixed (ob copy method), this branch adds a Create Series View menu item. Series created via this can then be subject to observation transformation operations, such as mag baseline shifter.

Then, once this has been reviewed and merged, I can move on to #49 to allow more series to be selected from for series creation, including the Filter series.

### CODE REVIEW

**Comment by mpyat2** [comment]
Hi @david, I see a strange behavior: the new series is not visible in the 'Observations' pane. Please see the video attached: https://www.youtube.com/watch?v=TNOLVJMtnEA

**Comment by dbenn** [comment]
> Hi @david, I see a strange behavior: the new series is not visible in the 'Observations' pane. Please see the video attached: https://www.youtube.com/watch?v=TNOLVJMtnEA

Thanks @mpyat2. Hmm. Yes. The answer will be in `VisibleSeriesRowFilter` I think. I did notice this awhile ago and then neglected to capture it! Thanks for picking it up!

**Comment by dbenn** [comment]
Please review the latest changes from that last commit @mpyat2. This seems to work.

**Review by mpyat2 — APPROVED** [review]

**Comment by mpyat2** [comment]
Thank you, @dbenn , it works now.

**Comment by mpyat2** [comment]
Hi @dbenn ,
New series created via "Create Series" are independent of the loaded data now. However, they behave differently. For example, they are not visible for the "Heliocentric JD converter plugin" (it takes observations from getLatestNewStarMessage). I'm not sure it is a bug, rather a feature (?).
Also, those new series seem not visible for filters created via "Simple filter...", "Vela Filter...", "Observer list filter...", and, probably, other filters (however, "Filter from plot" takes them).
Again, I'm not sure it is a "bug". What do you think? At least this behavior should be documented somewhere.

**Comment by dbenn** [comment]
Hi @mpyat2. Indeed. Thanks for this! I have captured this in #84 and a new issue, #253. I'm not sure whether the filter mechanism is a bug. I suspect it is, but it needs some thought/conversation, whereas I _do_ think the HJD behaviour is a bug since I can't see a good reason to disallow a user defined series from being kept separate re: HJD status from its original observations.

**Pull request merged**
