### PR TITLE
Issue 117 jfreechart update

### PR DESCRIPTION
**Pull request by mpyat2**
Issue #117: JFreeChart library updated to 1.5.2

### CODE REVIEW

**Review by dbenn — COMMENTED** [review]
Hi Max. Looks good but a question and a potential issue.

**Question**: is `public Dimension getPreferredSize()` a requirement of jfreechart 1.5.2 vs the old version? Are the width and height values chosen for particular reasons or just because something is needed and they seem reasonable in general?

**Issue**: I see a WWZ error dialog for the same dataset (a Kepler FITS file; will attach) with min period 0, max period 1, resolution 0.0001, everything else default in WWZ dialog) that I don't see with old jfreechart version. The data lends itself to a known problem in the WWZ implementation re: large gap in data. You end up with periods of 0 and so infinite frequencies (see top hits pane). The error occurs when you click the Frequency vs Time tab, presumably because of some difference in jfreechart's response to infinite values. Not a showstopper, just something to consider here and perhaps a new ticket.

Screen Shot 2021-03-20 at 08 58 15

[kplr010789273-2013131215648_llc.fits.zip](https://github.com/AAVSO/VStar/files/6174362/kplr010789273-2013131215648_llc.fits.zip)

**Comment by mpyat2** [comment]
Hi David,
'public Dimension getPreferredSize()' is for compatibility with default sizes of the old JfreeChart (1.0.xx).
Without it the default chart size is quite big:
image

getPreferredSize() sets the same size as for JfreeChart 1.0.xx:
image

Issue IllegalArgumentException: indeed, JFreeChart ignored the infinite axis value in ver 1.0.13. Check for the infinite axis size already exists in ver 1.0.19 (the last 1.0.xx version):

@Override
    public TickUnit getCeilingTickUnit(double size) {
        if (Double.isInfinite(size)) {
            **throw new IllegalArgumentException("Must be finite.");**
        }
        this.power = (int) Math.ceil(Math.log10(size));
        if (this.integers) {
            power = Math.max(this.power, 0);
        }
        this.factor = 1;
        boolean done = false;
        // step down in size until the current size is too small or there are 
        // no more units
        while (!done) {
            done = !previous();
            if (getTickSize() < size) {
                next();
                done = true;
            }
        }
        return new NumberTickUnit(getTickSize(), getTickLabelFormat(), 
                getMinorTickCount());
    }

This code is the same as in ver 1.5.2

**Comment by mpyat2** [comment]
@dbenn , please see the last commit to the issue-117-jfreechart-update branch.
This is a "cosmetic" fix. At least the exception does not occur immediately while switching tabs.
The infinite values still present so if the user chooses "Auto Range->Range Axis" from the pop-up menu, the exception occurs (and there are other ways to raise the exception).
It would be good to make changes in WWZ calculations to avoid infinity, for example, start calculations from 0+step if Minimum Period = 0 or do not allow the user to enter 0 as Minimum Period (with some warning message). This is for another branch of course.

**Review by dbenn — APPROVED** [review]
All looks good Max. I'm happy to merge this.

**Comment by dbenn** [comment]
I'll create another issue for this. There are multiple tix on WWZ I think; perhaps some from SourceForge to transfer yet.

**Comment by mpyat2** [comment]
Thank you!

**Pull request merged**
