### PR TITLE
#354: removed security policy setting in VStar GUI class; deprecated old applet class

### PR DESCRIPTION
**Pull request by dbenn**

### CODE REVIEW

**Review by mpyat2 — APPROVED** [review]
Hi @dbenn , I tested the build with your changes, and everything works.

I found a small glitch not connected to this change. There was another fix on 1 Jun 2023 in which the 'rm' call was included in the 'clean' target of the build.xml. It seems I have never executed 'ant clean' since then and did not notice it. Today I executed 'ant clean', which gave me a (non-critical) error:
```
C:\Personal\Projects\VStarGIT\VStar>ant clean
Buildfile: C:\Personal\Projects\VStarGIT\VStar\build.xml

clean:
     [exec] Execute failed: java.io.IOException: Cannot run program "rm" (in directory "C:\Personal\Projects\VStarGIT\VStar"): CreateProcess error=2

BUILD SUCCESSFUL
Total time: 5 seconds
```
'rm' does not exist in Windows. There is an almost equivalent to ```rm -rf``` command ```rd /s /q ```
Well, nothing fatal, some violation of perfection only.

**Comment by dbenn** [comment]
Thanks @mpyat2. The section of `build.xml` is:
~~~
    <!-- succeeeds where including VStar.app fileset or dirset above does not -->
    <exec failifexecutionfails="no" failonerror="no" executable="rm">
        <arg value="-rf" />
        <arg value="VStar.app" />
    </exec>
~~~
In principle it should not be necessary and I'm surprised that `failifexecutionfails="no"` doesn't have the desired effect. I could try putting `VStar.app` back in as a fileset again. I'll raise an issue for this.

**Comment by mpyat2** [comment]
Hi @dbenn ,
The 'failifexecutionfails="no"' does have the desired effect: see the 'BUILD SUCCESSFUL' message at the end of the log. However, ant also prints an error message that is pretty correct.
Well, except for this error message, everything works.

**Comment by dbenn** [comment]
Can you tell me what that error is @mpyat2 ? I don't see it on the Mac.

**Comment by mpyat2** [comment]
Hi @dbenn 
Well, I probably was not correct: this is not an error but rather an information message.
C:\Personal\Projects\VStarGIT\VStar>ant clean
Buildfile: C:\Personal\Projects\VStarGIT\VStar\build.xml

**clean:
     [exec] Execute failed: java.io.IOException: Cannot run program "rm" (in directory "C:\Personal\Projects\VStarGIT\VStar"): CreateProcess error=2**

BUILD SUCCESSFUL
Total time: 5 seconds

Of course, you do not see it on the Mac because it has the 'rm' command.

**Comment by dbenn** [comment]
Hi @mpyat2. So, are you still seeing that error/message? The `rm` command should not be used in the `clean` target in an `exec` task now and all file removal is being done via Ant `delete` tasks which would translate into `rm` or `del` or similar in the target OS.

**Comment by mpyat2** [comment]
Hi @dbenn , now everything is ok. See https://github.com/AAVSO/VStar/pull/361#pullrequestreview-1519434778

**Pull request merged**
