### PR TITLE
325 observation details are always strings

### PR DESCRIPTION
**Pull request by dbenn**
Hi @mpyat2 

There are quite a few changes on this branch and I'll have to sort out merge conflicts. The branch has changes from #317 and #325.

**EDIT**: The conflict was in `plugin/src/org/aavso/tools/vstar/external/plugin/ASASObservationSource.java` so could you please check that I have not messed anything up there? Seems OK.

David

### CODE REVIEW

**Comment by mpyat2** [comment]
Hi @dbenn ,
Thank you! I'll check it. I see some changes needed in ASASSNObservationSource.java, I'm working on them.

**Comment by mpyat2** [comment]
Hi @dbenn ,
please see my changes.

**Comment by dbenn** [comment]
Looks good @mpyat2. Do you have comments on my code on this branch?

**Review by mpyat2 — APPROVED** [review]
Hi @dbenn 
sorry for delay. Looks good.

**Comment by mpyat2** [comment]
Hi @dbenn ,
I've updated QLPFITSObservationSource.java (minimal changes) to make it compatible with the last Sector56 data. They changed column names!

**Comment by dbenn** [comment]
@mpyat2 I think we're OK to merge this now. Agreed? I have a working Mac again BTW. :)

**Review by dbenn — COMMENTED** [review]
Thanks @mpyat2

**Comment by mpyat2** [comment]
Hi @dbenn ,
yes, please merge it!

**Pull request merged**
