### PR TITLE
Issue 221 vela observation source plug in

### PR DESCRIPTION
**Pull request by mpyat2**
Known issue: The plug-in still cannot be used effectively in WebStart mode due to a lack of "file open" and "paste from clipboard" capabilities (security restrictions).

### CODE REVIEW

**Comment by dbenn** [comment]
Hi @mpyat2. Just looking at the pull request. Can you tell me more about VeLa XML files and the context here? Thanks.

**Comment by mpyat2** [comment]
In addition to the VeLa code, the plug-in requires parameters Minimum JD, Maximum JD, number of points to calculate, and type of Julian date (JD/HJD/BJD).
These additional parameters are saved along with the VeLa code in an XML file, see an example attached.

While loading a file, the plug-in tries to interpret it as XML, if failed, it loads it as plain text, so it is possible to load simple text files with VeLa code (like the VeLa model plug-in does).

@dbenn , please do not merge this branch with master now, I should test some possible encoding issues.

**Comment by dbenn** [comment]
Thank you for all of this @mpyat2! I'm starting to look at this.

**Review by dbenn — APPROVED** [review]
This all looks good Max. I'm wondering whether `.vlx` could/should be something like `.vmx` only because it's specifically for a VeLa model with additional data other than just VeLa code. I'm not too worried either way though.

As an aside, this kind of XML may help to inform the kind of "project" idea floated in #194.

**Comment by dbenn** [comment]
@mpyat2 I was going to create an issue to use one of your new save functions but notice at least in my English locale that it is saving and loading OK; I will at least fix the lambda symbol though as per #234

**Comment by mpyat2** [comment]
Thank you, @dbenn !
Concerning extension: I'm not sure what is better. Both extensions are used already by other products (it's hard to find something unique now). vmx = VMware Virtual Machine Configuration, "VLX files mostly belong to AutoCAD by Autodesk".
Probably, if we invent 4-char extension for it it could be unique... Currently, I have no idea. Anyway, we can change it anytime (before the release).

**Comment by dbenn** [comment]
Re: your 4 letter extension idea: `.vlmx`?

**Comment by dbenn** [comment]
Re: Ukranian comment, so sounds like we need an issue to fix this then.

**Comment by mpyat2** [comment]
@dbenn , when you have time, could you please merge this branch?

**Pull request merged**
