### PR TITLE
Issue #101 fix.

### PR DESCRIPTION
**Pull request by mpyat2**
See issue #101

### CODE REVIEW

**Comment by mpyat2** [comment]
Issue #101: cleanup code in windowClosing event: PeriodAnalysisDialogBase.java

**Review by dbenn — APPROVED** [review]

**Comment by dbenn** [comment]
Looks good. Thanks Max.

**Comment by mpyat2** [comment]
What about merging this with master?

**Comment by dbenn** [comment]
Sorry for the delay on this one @mpyat2

**Pull request merged**
